blank_issues_enabled: true
contact_links:
  - name: Recipe Visualizer Discussions
    url: https://github.com/benlbaum/recipe-visualization-tool/discussions
    about: For general questions and discussions about the Recipe Visualizer
