directories:
  output: release
  buildResources: assets
appId: com.yourcompany.recipetreevisualizer
productName: Recipe Tree Visualizer
files:
  - filter:
      - dist/**/*
      - electron.cjs
win:
  target:
    - nsis
    - portable
electronVersion: 32.0.1
